//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MVC_CRUD.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class student
    {
        public int rno { get; set; }
        public string name { get; set; }
        public Nullable<double> english { get; set; }
        public Nullable<double> math { get; set; }
        public Nullable<double> science { get; set; }
    }
}
